---
- name: "Automate Docker Build and Run Locally on EC2"
  hosts: ec2
  become: yes  # Run tasks as sudo
  tasks:
    - name: Stop running container
      command: docker stop frontend-task
      ignore_errors: yes

    - name: Remove stopped container
      command: docker rm frontend-task
      ignore_errors: yes

    - name: Remove used image
      command: docker rmi ahmedsalama3014/frontend-task:v1
      ignore_errors: yes

    - name: Copy application code to EC2
      copy:
        src: /home/control/depi-study/argoCD/My-cv-app/
        dest: /home/ubuntu/My-cv-app/
        remote_src: no

    - name: Build new image locally on EC2
      command: docker build -t ahmedsalama3014/frontend-task:v1 .
      args:
        chdir: /home/ubuntu/My-cv-app

    - name: Run new container locally on EC2
      command: docker run -d --name frontend-task -p 8020:80 ahmedsalama3014/frontend-task:v1
