---
- hosts: ec2
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        chmod +x minikube
        sudo mv minikube /usr/local/bin/
        sudo apt-get install -y conntrack  # Required for Minikube

    - name: Start Minikube
      shell: minikube start --driver=docker

    - name: Create Kubernetes namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: frontend-task

    - name: Apply deployment
      shell: kubectl apply -f deployment.yaml --namespace frontend-task

    - name: Apply services
      shell: kubectl apply -f services.yaml --namespace frontend-task
