---
- name: Prepare Environment on EC2
  hosts: frontend
  become: yes  # This ensures all tasks run with elevated privileges
  tasks:
    - name: Install Git
      apt:
        name: git
        state: present

    - name: Create directory for frontend application
      file:
        path: /home/ubuntu/frontend-task
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Clone project from GitHub
      git:
        repo: "https://github.com/Ahmed3019/my-cv-application.git"
        dest: /home/ubuntu/frontend-task/my-cv-application
        version: main

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present

    - name: Add user to the Docker group
      user:
        name: ubuntu
        group: docker
        append: yes

    - name: Restart Docker service
      service:
        name: docker
        state: restarted

    - name: Wait for Docker to be ready
      wait_for:
        port: 2375  # Default Docker port for the API
        state: started
        timeout: 30

    - name: Pull latest Docker image
      docker_image:
        name: ahmedsalama3014/frontend-task
        tag: latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: frontend-task
        image: ahmedsalama3014/frontend-task:latest
        state: started
        restart_policy: always
        published_ports:
          - "8020:80"

    - name: Print message when container is running
      debug:
        msg: "Container '{{ docker_image_name }}' is running as '{{ docker_container_name }}'"
      vars:
        docker_image_name: "ahmedsalama3014/frontend-task:latest"
        docker_container_name: "frontend-task"
