apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-deploy
  namespace: frontend-task
  labels: 
    app: survey-app  # Updated label to match the service selector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: survey-app
  template:
    metadata:
      labels:
        app: survey-app
    spec:
      containers:
        - name: survey-app
          image: ahmedsalama3014/frontend-task:latest  # Use 'latest' as the Jenkins file pushes the latest image
          ports:
            - containerPort: 80  # Port the container listens on
          resources:
            requests:
              memory: "256Mi"    # Minimum memory the container is guaranteed
              cpu: "250m"        # Minimum CPU the container is guaranteed
            limits:
              memory: "512Mi"     # Maximum memory the container can use
              cpu: "500m"         # Maximum CPU the container can use
