apiVersion: v1
kind: Service
metadata:
  name: frontend-task
  namespace: frontend-task
  labels:
    app: frontend-task
spec:
  selector:
    app: survey-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80

