apiVersion: v1
kind: Service
metadata:
  name: frontend-task
  namespace: frontend-task
  labels:
    app: frontend-task
spec:
  selector:
    app: survey-app  # Should match the app label in deployment
  type: NodePort
  ports:
    - port: 8020      # The port that will be exposed
      targetPort: 80  # The port the container listens on
